### ISSUE TITLE
Sanitizer could get confused adding another item into an array

### ISSUE THREAD

**Issue by Kaixiang** [pivotal-cloudops/secrets-sanitizer#11]
Here is an example:

you have a sanitized manifest looks like below:

```
secrets:
- username: usernameA
   password: "{{secrets_1_password}}"
- username: usernameB
   password: "{{secrets_2_password}}"
```

After adding another items between userA and userB like below and sanitize it again, you will get

```
secrets:
- username: usernameA
   password: "{{secrets_1_password}}"
- username: username_slip
   password: "{{secrets_2_password}}"
- username: usernameB
   password: "{{secrets_2_password}}"
```

this will change the value of password of usernameB after desensitize, which lead to unexpected behavior.

probably using uuid instead of index number will resolve this issue.
